### ISSUE TITLE
Fix the images that aren't loading completely in the README.md file

### ISSUE THREAD

**Issue by raghavTinker** [Servatom/Notion-DiscordBot#42]
Fix the images that aren't loading in the README.md file

**Comment by jmakhack** [comment]
Hi @raghavTinker, I can pick up this issue if available.

**Comment by raghavTinker** [comment]
Go ahead :)

**Comment by nayan2306** [comment]
> Fix the images that aren't loading in the README.md file

Can I do that?

**Comment by raghavTinker** [comment]
Go ahead..give it a try! :)

**Comment by nayan2306** [comment]
Can I Get this iamges?

**Comment by raghavTinker** [comment]
The links are in the README file only

**Comment by nayan2306** [comment]
okay

**Comment by Hussain6** [comment]
Can I pick this issue?

**Comment by raghavTinker** [comment]
Sure go ahead :)

**Comment by jmakhack** [comment]
@raghavTinker I just created PR #43 to just fix the notion + discord main image so the other assignees can work on the other broken images.

**Comment by nayan2306** [comment]
@raghavTinker I have add all the images and update the readme file can you check it once?
