### ISSUE TITLE
Google_Drive_Setup README.md

### ISSUE THREAD

**Issue by nayan2306** [Servatom/Notion-DiscordBot#49]
the images are not shown Can you please assign me the task I will update it.

**Comment by raghavTinker** [comment]
Yes!
Just change the URL from `https://servatom.com/assets` to `https://assets.servatom.com/`
Example:
```https://servatom.com/assets/GDriveAPI/Screenshot%202021-07-09%20at%2012.33.23%20PM.png``` should be converted to 
```https://assets.servatom.com/GDriveAPI/Screenshot%202021-07-09%20at%2012.33.23%20PM.png```

**Comment by nayan2306** [comment]
Done from my side @raghavTinker please check it once
