### ISSUE TITLE
Error when adding an item to the db

### ISSUE THREAD

**Issue by faceslog** [Servatom/Notion-DiscordBot#51]
Hi I just tried to install properly the bot via docker / and in a local env but I'm getting the same error everytime I run the add cmd:

```py
Ignoring exception in command add:
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.7/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "bot.py", line 36, in add
    if((doesItExist(url) == False) and (amIThere(url) == False)):
  File "/home/user/notion/Notion-DiscordBot/Bot/duplicateCheck.py", line 31, in amIThere
    with open("./Bot/dataUploaded.txt") as log:
FileNotFoundError: [Errno 2] No such file or directory: './Bot/dataUploaded.txt'
```

I decided to remove the "Bot/"  in line 31 in `Bot/duplicateCheck.py`  
I replaced `with open("./Bot/dataUploaded.txt") as log:` to `with open("./dataUploaded.txt") as log:` and now everything is working fine.

Regards

**Comment by raghavTinker** [comment]
Were you running this in a container?

**Comment by faceslog** [comment]
Yes and the error still occured without using docker

**Comment by raghavTinker** [comment]
Yeah actually this was an issue
thanks for letting us know!
Will fix it!

**Comment by raghavTinker** [comment]
The issue has been fixed so will be closing the issue.
Thanks for letting us know!
