### ISSUE TITLE
I can't run it

### ISSUE THREAD

**Issue by usarral** [Servatom/Notion-DiscordBot#52]
I have installed all the requeriments, but when i try to run, i get that error
![image](https://user-images.githubusercontent.com/41452910/145854015-15d81a0d-d893-484e-b177-208804289955.png)

**Comment by raghavTinker** [comment]
It should work.....this seems to be your own system issue.
Have you installed discord.py for python3?
Also, its recommended running in a virtual environment better in a containerized manner
