### ISSUE TITLE
Write python unit tests.

### ISSUE THREAD

**Issue by rdotjain** [Servatom/Notion-DiscordBot#8]

**Comment by manoloesparta** [comment]
I can work in this but I think we should split it into several PRs since there is a lot of ground to cover.

**Comment by nayan2306** [comment]
Can I work on this can you tell me in detail what I need to do?

**Comment by raghavTinker** [comment]
sure go ahead :)

**Comment by nayan2306** [comment]
Can you berif it once what I need to do?

**Comment by raghavTinker** [comment]
Actually, we aren't sure how this can be done and the correct way to write this test. So for the time being I am closing this issue and sometime in the near future we will open it up again
